### ISSUE TITLE
Unhandled promise rejection error

### ISSUE THREAD

**Issue by davidfurlong** [bluebill1049/react-simple-img#30] opened 2018-09-29 09:07 UTC
This library is throwing unhandled promise rejection errors - I suspect possibly here when image loading fails: https://github.com/bluebill1049/react-simple-img/blob/4599a9b5e6d735749fa85169aa7d31d1579e6054/src/utils/fetchImage.js#L4

```zsh
Unhandled promise rejection 
error
​
bubbles: false
​
cancelBubble: false
​
cancelable: false
​
composed: false
​
currentTarget: null
​
defaultPrevented: false
​
eventPhase: 0
​
explicitOriginalTarget: <img src="">
​
isTrusted: true
​
originalTarget: <img src="">
​
srcElement: <img src="">
​
target: <img src="">
​
timeStamp: 30636
​
type: "error"
​
<prototype>: EventPrototype { composedPath: composedPath(), stopPropagation: stopPropagation(), stopImmediatePropagation: stopImmediatePropagation(), … }
es6.promise.js:110
onUnhandled/</result<
es6.promise.js:110
module.exports
_perform.js:3:12
onUnhandled/<
es6.promise.js:104
module.exports
_invoke.js:5
<anonymous>
_task.js:35
run
_task.js:21
listener
_task.js:25
```

**Comment by bluebill1049** [comment] 2018-09-29 10:27
This happens when images loading fails, i will investigate why this is happening.

**Comment by bluebill1049** [comment] 2018-09-29 10:57
looks like image src tag is empty, i have fixed the `Unhandled promise rejection error`. will be release on the next patch include your PR.

**Comment by bluebill1049** [comment] 2018-10-02 11:16
This should be resolved by the latest patch

**Comment by davidfurlong** [comment] 2018-10-02 11:41
Unfortunately I dont think this has fixed the problem. I'm getting a

```
Unhandled promise rejection Error: "💩 Fetch image failed with target <img
class="card-img-top card_image" alt="Sailing on IJsselmeer and Wad and
being a volunteer? That's possible at SailWise" src="
https://deedmob-prod.imgix.net/job_3044089_1520252877899%40300x168?auto=format&amp;w=250&amp;h=140&amp;fit=crop&amp;blur=60&amp;q=10"
srcset="" data-src="
https://deedmob-prod.imgix.net/job_3044089_1520252877899%40300x168?auto=format&amp;w=250&amp;h=140&amp;fit=crop"
data-srcset="
https://deedmob-prod.imgix.net/job_3044089_1520252877899%40300x168?auto=format&amp;w=250&amp;h=140&amp;fit=crop
1x,
https://deedmob-prod.imgix.net/job_3044089_1520252877899%40300x168?auto=format&amp;w=250&amp;h=140&amp;fit=crop&amp;q=45&amp;dpr=2
2x,
https://deedmob-prod.imgix.net/job_3044089_1520252877899%40300x168?auto=format&amp;w=250&amp;h=140&amp;fit=crop&amp;q=30&amp;dpr=3
3x" width="250" height="140"> and error message { "isTrusted": true }"
```

**Comment by bluebill1049** [comment] 2018-10-02 21:57
@davidfurlong do you know how to reproduce this issue?

**Comment by bluebill1049** [comment] 2018-10-03 01:05
right now if the image fetch failed will throw an Error, i am thinking of changing it into `console.error`

**Comment by davidfurlong** [comment] 2018-10-03 07:07
Right so I think that's the issue I'm experiencing. I'm not sure throwing
an error on image fetch fail is the best practice, as its not really
possible for me to catch the error implementing the library. Perhaps there
should be a prop onFetchFailed or something so the implementer can manually
retry, show a placeholder or handle it themselves

**Comment by bluebill1049** [comment] 2018-10-03 10:56
sounds good to me i will change console.error for the next path, and will looking into the suggestion you have replied.

**Comment by bluebill1049** [comment] 2018-10-03 11:00
https://github.com/bluebill1049/react-simple-img/releases/tag/v1.4.3

**Comment by davidfurlong** [comment] 2018-11-09 08:47
Hey Bill, sorry for the delay.
The error is now logged into the console, which is not ideal for production apps either.
My main issue is that is seems to occur when the load hasn't failed, and the error is empty.
An example:
```
💩 Fetch image failed with target

<img class="card-img-top card_image" alt="sfdsdfsd" src="https://deedmob-dev-images.s3.eu-west-1.amazonaws.com/job_1_1541549476091%40300x168" srcset="" data-src="https://deedmob-dev-images.s3.eu-west-1.amazonaws.com/job_1_1541549476091%40300x168" style="visibility: visible;" width="250" height="140">

and error message {}
```

**Comment by bluebill1049** [comment] 2018-11-09 20:48
hi @davidfurlong,

i have reproduced the error in production, this will happen when routes change and images not finished loading. in terms of empty error message, i haven't seem that before. (`srcSet` is not required.)  

how many of those empty errors do you get in prod? how often does that happens. if it's due to route change then it's fine, i will take a look in the meantime.

**Comment by davidfurlong** [comment] 2018-11-12 13:42
Yeah `when routes change and images not finished loading` sounds likely to be causing this for us then. Thanks for looking into it!

**Comment by bluebill1049** [comment] 2018-11-12 23:03
hey @davidfurlong, so the error message is always empty object? can you share more error logs? I can look into it bit more. 👍

**Closed** 2018-11-20 00:15 UTC

**Comment by dima-f1** [comment] 2019-02-19 21:20
Man, I can't understand why are you log errors to browser console, especially with content like this:

`
💩 Fetch image failed with target
<img src="data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=" srcset="" data-src="https://randomfileimage.jpeg" style="visibility: hidden;">
and error message {
  "isTrusted": true
}
`

Thats really annoying and makes this library not production ready. I hope you will fix this issue because in all other respects this library looks great

**Comment by bluebill1049** [comment] 2019-03-24 07:52
sorry just saw this message, i will fix that in the next patch.
